[build]
builder = "nixpacks"
buildCommand = """
pip install -r requirements.txt
mkdir -p data
"""

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100 
